# Generated by Django 3.0.2 on 2020-01-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('photo', models.ImageField(upload_to='members_profile')),
            ],
        ),
    ]
